CREATE TABLE `user_membership_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `user_membership_id` int NOT NULL,
  `category_type` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `item_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plu` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `adult_qty` tinyint(1) DEFAULT NULL,
  `child_qty` tinyint DEFAULT NULL,
  `parking` tinyint(1) DEFAULT NULL,
  `iu` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `car_plate` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `membership_photo` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Photo URL',
  `member_first_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `member_last_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `member_email` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `member_dob` datetime DEFAULT NULL,
  `member_country` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `member_identification_no` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `member_phone_number` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `co_member` json DEFAULT NULL,
  `valid_from` datetime DEFAULT NULL,
  `valid_until` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_membership_id` (`user_id`,`user_membership_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_membership_id` (`user_membership_id`),
  KEY `idx_member_email` (`member_email`),
  CONSTRAINT `fk_membership_id` FOREIGN KEY (`user_membership_id`) REFERENCES `user_memberships` (`id`),
  CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;