CREATE TABLE user_membership_details (
    id INT(11) NOT NULL AUTO_INCREMENT,
    user_id INT(11) NOT NULL,
    user_membership_id INT(11) NOT NULL,
    category_type VARCHAR(256) NOT NULL,
    item_name VARCHAR(256) NOT NULL,
    plu VARCHAR(256) NULL DEFAULT NULL,
    adult_qty TINYINT(1) NULL DEFAULT NULL,
    child_qty TINYINT(2) NULL DEFAULT NULL,
    parking TINYINT(1) NULL DEFAULT NULL,
    iu VARCHAR(24) NULL DEFAULT NULL,
    car_plate VARCHAR(24) NULL DEFAULT NULL,
    membership_photo VARCHAR(512) NULL DEFAULT NULL,
    member_first_name VARCHAR(256) NULL DEFAULT NULL,
    member_last_name VARCHAR(256) NULL DEFAULT NULL,
    member_email VARCHAR(256) NULL DEFAULT NULL,
    member_dob timestamp NULL DEFAULT NULL,
    member_country VARCHAR(50) NULL DEFAULT NULL,
    member_identification_no VARCHAR(10) NULL DEFAULT NULL,
    member_phone_number VARCHAR(256) NULL DEFAULT NULL,
    co_member JSON NULL DEFAULT NULL,
    valid_from timestamp NULL DEFAULT NULL,
    valid_until timestamp NULL DEFAULT NULL,
    created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY unique_membership_id (user_id, user_membership_id),
    KEY idx_user_id (user_id),
    KEY idx_membership_id (user_membership_id),
    KEY idx_member_email (member_email),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_membership_id FOREIGN KEY (user_membership_id) REFERENCES user_memberships(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;