module.exports = {
  en: {
    signup_email:
      "This email address is already being used for a Mandai Account.",
    signup_firstName: "The first name is invalid.",
    signup_lastName: "The last name is invalid.",
    signup_dob:
      "The date of birth is invalid. Must between 13 and 99 years old.",
    signup_group: "The group is invalid.",
    signup_newsletter: "Must agree and subscribe to the newsletter.",
    signup_country: "Country is invalid.",
    signup_phoneNumber: "Phone number is invalid.",
    signup_password: "Password does not meet complexity requirements.",
    signup_confirmPassword: "Passwords do not match.",
    signup_success: "New user signed up successfully.",
    signup_error: "New user signup error.",
    login_success: "Login success.",
    email_no_record: "No record found.",
    membership_email_invalid: "Requested email is invalid or empty.",
    logout_success: "Logout success.",
    membership_get_success: "Get membership success.",
    email_being_used:
      "This email address is already being used for a Mandai Account.",
    firstName_invalid: "The first name is invalid.",
    lastName_invalid: "The last name is invalid.",
    dob_invalid:
      "The date of birth is invalid. Must between 13 and 99 years old.",
    group_invalid: "The group is invalid.",
    newsletter_invalid: "Must agree and subscribe to the newsletter.",
    country_invalid: "Country is invalid.",
    phoneNumber_invalid: "Phone number is invalid.",
    email_not_being_used: "This email address does not have a Mandai Account.",
    password_invalid: "Password does not meet complexity requirements.",
    confirmPassword_invalid: "Passwords do not match.",
    update_success: "User info updated successfully.",
    update_user_error: "User info update error.",
    old_password_invalid: "Old password do not match.",
    unauthorized: "Unauthorized",
    request_reset_password_success: "Password reset link sent to your email",
    confirm_reset_password_success: "Password successfully reset.",
    token_reset_password_being_used: "Token has already been used.",
    newPassword_required: "Password is required.",
    newPassword_invalid: "Password does not meet complexity requirements.",
    passwordToken_required: "Token is required.",
    passwordToken_invalid: "Requested token is invalid or empty.",
    token_valid: "Token is valid.",
    passwordToken_expired: "Requested token has expired.",
    cognito_user_not_exist: "This email address does not have a Cognito user.",
    db_email_not_exist: "This email address does not have a Mandai account.",
    db_user_membership_not_exist:
      "This Visual ID does not have a user membership.",
    db_user_membership_create_error: "Failed to create user membership.",
    db_membership_details_create_error: "Failed to create membership details.",
    db_user_membership_update_error: "Failed to update user membership.",
    db_membership_details_update_error: "Failed to update membership details.",
    membership_pass_create_success: "Successfully created membership pass.",
    membership_pass_update_success: "Successfully updated membership pass.",
    membership_pass_create_error: "Failed to create membership pass.",
    membership_pass_update_error: "Failed to update membership pass.",
    membership_pass_cognito_error:
      "Failed to update membership pass details on Cognito.",
    membership_pass_s3_error: "Failed to upload membership photo to S3.",
    membership_pass_sqs_error: "Failed to send SQS message.",
    membership_pass_email: "The email is empty or invalid.",
    membership_pass_mandaiId: "The Mandai ID is empty or invalid.",
    membership_pass_group: "The group is empty or invalid.",
    membership_pass_passType: "The pass type is empty or invalid.",
    membership_pass_visualId: "The Visual ID is empty or invalid.",
    membership_pass_categoryType: "The Category Type is empty or invalid.",
    membership_pass_adultQty: "The Adult Qty is empty or invalid.",
    membership_pass_childQty: "The Child Qty is empty or invalid.",
    membership_pass_member_dob: "The Member DOB is invalid.",
    membership_pass_parking: "The parking is invalid.",
    membership_pass_iu: "The IU number is invalid.",
    membership_pass_carPlate: "The car plate number is invalid.",
    membership_pass_member: "The member data is empty or invalid.",
    membership_pass_coMembers: "The co-members data is empty or invalid.",
    membership_pass_membershipPhoto: "The photo data is empty or invalid.",
  },
  zh: {
    signup_email: "此电子邮件地址已被用于 Mandai 帐户。",
    signup_firstName: "名字无效。",
    signup_lastName: "姓氏无效。",
    signup_dob: "出生日期无效。年龄必须在 13 至 99 岁之间。",
    signup_group: "该群组无效。",
    signup_newsletter: "必须同意并订阅新闻通讯。",
    signup_country: "国家无效。",
    signup_phoneNumber: "电话号码无效。",
    signup_password: "密码不符合复杂性要求。",
    signup_confirmPassword: "密码不匹配。",
    signup_success: "新用户注册成功。",
    signup_error: "新用户注册错误。",
    login_success: "登录成功。",
    email_no_record: "未找到记录。",
    membership_email_invalid: "请求的电子邮件无效或为空。",
    logout_success: "注销成功.",
    membership_get_success: "获取会员资格成功.",
    email_being_used: "此电子邮件地址已被用于 Mandai 帐户。",
    firstName_invalid: "名字无效。",
    lastName_invalid: "姓氏无效。",
    dob_invalid: "出生日期无效。年龄必须在 13 至 99 岁之间。",
    group_invalid: "该群组无效。",
    newsletter_invalid: "必须同意并订阅新闻通讯。",
    country_invalid: "国家无效。",
    phoneNumber_invalid: "电话号码无效。",
    email_not_being_used: "此邮箱地址没有 Mandai 账户。",
    password_invalid: "密码不符合复杂性要求。",
    confirmPassword_invalid: "密码不匹配。",
    update_success: "用户信息已成功更新。",
    update_user_error: "用户信息更新错误。",
    old_password_invalid: "旧密码不匹配。",
    unauthorized: "未授权",
    request_reset_password_success: "密码重置链接已发送到您的邮箱。",
    confirm_reset_password_success: "密码已成功重置。",
    token_reset_password_being_used: "令牌已被使用。",
    newPassword_required: "需要密码。",
    newPassword_invalid: "密码不符合复杂性要求。",
    passwordToken_required: "需要令牌。",
    passwordToken_invalid: "请求的令牌无效或为空。",
    token_valid: "令牌有效。",
    passwordToken_expired: "请求的令牌已过期。",
    cognito_user_not_exist: "此电子邮件地址没有对应的 Cognito 用户。",
    db_email_not_exist: "此电子邮件地址没有对应的 Mandai 账户。",
    db_user_membership_not_exist: "此视觉 ID 没有用户会员资格。",
    db_user_membership_create_error: "创建用户会员资格失败。",
    db_membership_details_create_error: "创建会员详细信息失败。",
    db_user_membership_update_error: "更新用户会员资格失败。",
    db_membership_details_update_error: "更新会员详细信息失败。",
    membership_pass_create_success: "会员证创建成功。",
    membership_pass_update_success: "会员证更新成功。",
    membership_pass_create_error: "创建会员证失败。",
    membership_pass_update_error: "更新会员证失败。",
    membership_pass_cognito_error: "更新 Cognito 中的会员证详细信息失败。",
    membership_pass_s3_error: "将会员照片上传到 S3 失败。",
    membership_pass_sqs_error: "发送 SQS 消息失败。",
    membership_pass_email: "电子邮件为空或无效。",
    membership_pass_mandaiId: "Mandai ID 为空或无效。",
    membership_pass_group: "组别为空或无效。",
    membership_pass_passType: "通行证类型为空或无效。",
    membership_pass_visualId: "视觉 ID 为空或无效。",
    membership_pass_categoryType: "类别类型为空或无效。",
    membership_pass_adultQty: "成人数量为空或无效。",
    membership_pass_childQty: "儿童数量为空或无效。",
    membership_pass_member_dob: "会员出生日期无效。",
    membership_pass_parking: "停车信息无效。",
    membership_pass_iu: "IU 编号无效。",
    membership_pass_carPlate: "车牌号无效。",
    membership_pass_member: "会员数据为空或无效。",
    membership_pass_coMembers: "共同会员数据为空或无效。",
    membership_pass_membershipPhoto: "照片数据为空或无效。",
  },
  kr: {
    signup_email: "이 이메일 주소는 이미 Mandai 계정에서 사용 중입니다.",
    signup_firstName: "이름이 유효하지 않습니다.",
    signup_lastName: "성을 입력한 값이 유효하지 않습니다.",
    signup_dob:
      "생년월일이 유효하지 않습니다. 만 13세 이상 99세 이하이어야 합니다.",
    signup_group: "그룹이 유효하지 않습니다.",
    signup_newsletter: "뉴스레터에 동의하고 구독해야 합니다.",
    signup_country: "국가가 유효하지 않습니다.",
    signup_phoneNumber: "전화번호가 유효하지 않습니다.",
    signup_password: "비밀번호가 일치하지 않습니다.",
    signup_confirmPassword: "비밀번호가 일치하지 않습니다.",
    signup_success: "기록을 찾을 수 없습니다.",
    signup_error: "새 사용자 등록 오류입니다.",
    login_success: "로그인 성공.",
    email_no_record: "기록을 찾을 수 없습니다.",
    membership_email_invalid: "요청된 이메일이 유효하지 않거나 비어 있습니다.",
    logout_success: "로그아웃 성공.",
    membership_get_success: "멤버십 획득 성공.",
    email_invalid: "이 이메일 주소는 이미 Mandai 계정에서 사용 중입니다.",
    firstName_invalid: "이름이 유효하지 않습니다.",
    lastName_invalid: "성을 입력한 값이 유효하지 않습니다.",
    dob: "생년월일이 유효하지 않습니다. 만 13세 이상 99세 이하이어야 합니다.",
    group_invalid: "그룹이 유효하지 않습니다.",
    newsletter_invalid: "뉴스레터에 동의하고 구독해야 합니다.",
    country_invalid: "국가가 유효하지 않습니다.",
    phoneNumber_invalid: "전화번호가 유효하지 않습니다.",
    email_not_being_used:
      "이 이메일 주소는 Mandai 계정을 가지고 있지 않습니다.",
    password_invalid: "비밀번호가 일치하지 않습니다.",
    confirmPassword_invalid: "비밀번호가 일치하지 않습니다.",
    update_success: "사용자 정보가 성공적으로 업데이트되었습니다.",
    update_user_error: "사용자 정보 업데이트 오류.",
    old_password_invalid: "기존 비밀번호가 일치하지 않습니다.",
    unauthorized: "권한 없음",
    request_reset_password_success:
      "비밀번호 재설정 링크가 이메일로 전송되었습니다.",
    confirm_reset_password_success: "비밀번호가 성공적으로 재설정되었습니다.",
    token_reset_password_being_used: "토큰이 이미 사용되었습니다.",
    newPassword_required: "비밀번호가 필요합니다.",
    newPassword_invalid: "비밀번호가 일치하지 않습니다.",
    passwordToken_required: "토큰이 필요합니다.",
    passwordToken_invalid: "요청된 토큰이 유효하지 않거나 비어 있습니다.",
    token_valid: "토큰이 유효합니다.",
    passwordToken_expired: "요청한 토큰이 만료되었습니다.",
    cognito_user_not_exist:
      "이 이메일 주소에 해당하는 Cognito 사용자가 없습니다.",
    db_email_not_exist: "이 이메일 주소에 해당하는 Mandai 계정이 없습니다.",
    db_user_membership_not_exist: "이 비주얼 ID에 사용자 멤버십이 없습니다.",
    db_user_membership_create_error: "사용자 멤버십 생성에 실패했습니다.",
    db_membership_details_create_error: "멤버십 세부정보 생성에 실패했습니다.",
    db_user_membership_update_error: "사용자 멤버십 업데이트에 실패했습니다.",
    db_membership_details_update_error:
      "멤버십 세부정보 업데이트에 실패했습니다.",
    membership_pass_create_success: "회원권이 성공적으로 생성되었습니다.",
    membership_pass_update_success: "회원권이 성공적으로 업데이트되었습니다.",
    membership_pass_create_error: "회원권 생성에 실패했습니다.",
    membership_pass_update_error: "회원권 업데이트에 실패했습니다.",
    membership_pass_cognito_error:
      "Cognito의 회원권 세부정보 업데이트에 실패했습니다.",
    membership_pass_s3_error: "회원 사진을 S3에 업로드하는 데 실패했습니다.",
    membership_pass_sqs_error: "SQS 메시지 전송에 실패했습니다.",
    membership_pass_email: "이메일이 비어 있거나 유효하지 않습니다.",
    membership_pass_mandaiId: "Mandai ID가 비어 있거나 유효하지 않습니다.",
    membership_pass_group: "그룹이 비어 있거나 유효하지 않습니다.",
    membership_pass_passType: "패스 유형이 비어 있거나 유효하지 않습니다.",
    membership_pass_visualId: "비주얼 ID가 비어 있거나 유효하지 않습니다.",
    membership_pass_categoryType:
      "카테고리 유형이 비어 있거나 유효하지 않습니다.",
    membership_pass_adultQty: "성인 수량이 비어 있거나 유효하지 않습니다.",
    membership_pass_childQty: "아동 수량이 비어 있거나 유효하지 않습니다.",
    membership_pass_member_dob: "회원 생년월일이 유효하지 않습니다.",
    membership_pass_parking: "주차 정보가 유효하지 않습니다.",
    membership_pass_iu: "IU 번호가 유효하지 않습니다.",
    membership_pass_carPlate: "차량 번호판이 유효하지 않습니다.",
    membership_pass_member: "회원 데이터가 비어 있거나 유효하지 않습니다.",
    membership_pass_coMembers:
      "공동 회원 데이터가 비어 있거나 유효하지 않습니다.",
    membership_pass_membershipPhoto:
      "사진 데이터가 비어 있거나 유효하지 않습니다.",
  },
  ja: {
    signup_email:
      "このメールアドレスはすでにMandaiアカウントで使用されています。",
    signup_firstName: "名前が無効です。",
    signup_lastName: "苗字が無効です。",
    signup_dob: "生年月日が無効です。13歳以上99歳以下である必要があります。",
    signup_group: "グループが無効です。",
    signup_newsletter: "ニュースレターに同意して購読する必要があります。",
    signup_country: "国が無効です。",
    signup_phoneNumber: "電話番号が無効です。",
    signup_password: "パスワードが複雑性の要件を満たしていません。",
    signup_confirmPassword: "パスワードが一致しません。",
    signup_success: "記録が見つかりませんでした。",
    signup_error: "新規ユーザー登録エラーです。",
    login_success: "ログイン成功。",
    email_no_record: "記録が見つかりません。",
    membership_email_invalid: "要求されたメールアドレスが無効または空です。",
    logout_success: "ログアウト成功.",
    membership_get_success: "メンバーシップ取得成功.",
    email_invalid:
      "このメールアドレスはすでにMandaiアカウントで使用されています。",
    firstName_invalid: "名前が無効です。",
    lastName_invalid: "苗字が無効です。",
    dob_invalid: "生年月日が無効です。13歳以上99歳以下である必要があります。",
    group_invalid: "グループが無効です。",
    newsletter_invalid: "ニュースレターに同意して購読する必要があります。",
    country_invalid: "国が無効です。",
    phoneNumber_invalid: "電話番号が無効です。",
    email_not_being_used:
      "このメールアドレスはMandaiアカウントを持っていません。",
    password_invalid: "パスワードが複雑性の要件を満たしていません。",
    confirmPassword_invalid: "パスワードが一致しません。",
    update_success: "ユーザー情報が正常に更新されました。",
    update_user_error: "ユーザー情報の更新エラー。",
    old_password_invalid: "古いパスワードが一致しません。",
    unauthorized: "未承認",
    request_reset_password_success:
      "パスワードリセットリンクをメールに送信しました。",
    confirm_reset_password_success: "パスワードが正常にリセットされました。",
    token_reset_password_being_used: "トークンは既に使用されています。",
    newPassword_required: "パスワードが必要です。",
    newPassword_invalid: "パスワードが複雑性の要件を満たしていません。",
    passwordToken_required: "トークンが必要です。",
    passwordToken_invalid: "要求されたトークンが無効か空です。",
    token_valid: "トークンは有効です。",
    passwordToken_expired: "リクエストされたトークンが期限切れです。",
    cognito_user_not_exist:
      "このメールアドレスには Cognito ユーザーが存在しません。",
    db_email_not_exist:
      "このメールアドレスには Mandai アカウントが存在しません。",
    db_user_membership_not_exist:
      "このビジュアル ID にはユーザー会員資格がありません。",
    db_user_membership_create_error: "ユーザー会員資格の作成に失敗しました。",
    db_membership_details_create_error: "会員詳細の作成に失敗しました。",
    db_user_membership_update_error: "ユーザー会員資格の更新に失敗しました。",
    db_membership_details_update_error: "会員詳細の更新に失敗しました。",
    membership_pass_create_success: "会員証の作成に成功しました。",
    membership_pass_update_success: "会員証の更新に成功しました。",
    membership_pass_create_error: "会員証の作成に失敗しました。",
    membership_pass_update_error: "会員証の更新に失敗しました。",
    membership_pass_cognito_error: "Cognito の会員証詳細の更新に失敗しました。",
    membership_pass_s3_error: "会員写真の S3 へのアップロードに失敗しました。",
    membership_pass_sqs_error: "SQS メッセージの送信に失敗しました。",
    membership_pass_email: "メールアドレスが空または無効です。",
    membership_pass_mandaiId: "Mandai ID が空または無効です。",
    membership_pass_group: "グループが空または無効です。",
    membership_pass_passType: "パスタイプが空または無効です。",
    membership_pass_visualId: "ビジュアル ID が空または無効です。",
    membership_pass_categoryType: "カテゴリタイプが空または無効です。",
    membership_pass_adultQty: "大人の数が空または無効です。",
    membership_pass_childQty: "子供の数が空または無効です。",
    membership_pass_member_dob: "会員の生年月日が無効です。",
    membership_pass_parking: "駐車情報が無効です。",
    membership_pass_iu: "IU 番号が無効です。",
    membership_pass_carPlate: "車両ナンバーが無効です。",
    membership_pass_member: "会員データが空または無効です。",
    membership_pass_coMembers: "共同会員データが空または無効です。",
    membership_pass_membershipPhoto: "写真データが空または無効です。",
  },
};
