module.exports = {
  en: {
    signup_email:
      "This email address is already being used for a Mandai Account.",
    signup_success: "New user signed up successfully.",
    signup_error: "New user signup error.",
    login_success: "Login success.",
    email_no_record: "No record found.",
    membership_email_invalid: "Requested email is invalid or empty.",
    logout_success: "Logout success.",
    membership_get_success: "Get membership success.",
    email_being_used:
      "This email address is already being used for a Mandai Account.",
    firstName_invalid: "The first name is invalid.",
    lastName_invalid: "The last name is invalid.",
    dob_invalid:
      "The date of birth is invalid. Must between 13 and 99 years old.",
    group_invalid: "The group is invalid.",
    newsletter_invalid: "Must agree and subscribe to the newsletter.",
    country_invalid: "Country is invalid.",
    phoneNumber_invalid: "Phone number is invalid.",
    email_not_being_used: "This email address does not have a Mandai Account.",
    password_invalid: "Password does not meet complexity requirements.",
    confirmPassword_invalid: "Passwords do not match.",
    update_success: "User info updated successfully.",
    update_user_error: "User info update error.",
    old_password_invalid: "Old password do not match.",
    unauthorized: "Unauthorized",
    request_reset_password_success: "Password reset link sent to your email",
    confirm_reset_password_success: "Password successfully reset.",
    token_reset_password_being_used: "Token has already been used.",
    newPassword_required: "Password is required.",
    newPassword_invalid: "Password does not meet complexity requirements.",
    passwordToken_required: "Token is required.",
    passwordToken_invalid: "Requested token is invalid or empty.",
    token_valid: "Token is valid.",
    passwordToken_expired: "Requested token has expired."
  },
  zh: {
    signup_email: "此电子邮件地址已被用于 Mandai 帐户。",
    signup_success: "新用户注册成功。",
    signup_error: "新用户注册错误。",
    login_success: "登录成功。",
    email_no_record: "未找到记录。",
    membership_email_invalid: "请求的电子邮件无效或为空。",
    logout_success: "注销成功.",
    membership_get_success: "获取会员资格成功.",
    email_being_used: "此电子邮件地址已被用于 Mandai 帐户。",
    firstName_invalid: "名字无效。",
    lastName_invalid: "姓氏无效。",
    dob_invalid: "出生日期无效。年龄必须在 13 至 99 岁之间。",
    group_invalid: "该群组无效。",
    newsletter_invalid: "必须同意并订阅新闻通讯。",
    country_invalid: "国家无效。",
    phoneNumber_invalid: "电话号码无效。",
    email_not_being_used: "此邮箱地址没有 Mandai 账户。",
    password_invalid: "密码不符合复杂性要求。",
    confirmPassword_invalid: "密码不匹配。",
    update_success: "用户信息已成功更新。",
    update_user_error: "用户信息更新错误。",
    old_password_invalid: "旧密码不匹配。",
    unauthorized: "未授权",
    request_reset_password_success: "密码重置链接已发送到您的邮箱。",
    confirm_reset_password_success: "密码已成功重置。",
    token_reset_password_being_used: "令牌已被使用。",
    newPassword_required: "需要密码。",
    newPassword_invalid: "密码不符合复杂性要求。",
    passwordToken_required: "需要令牌。",
    passwordToken_invalid: "请求的令牌无效或为空。",
    token_valid: "令牌有效。",
    passwordToken_expired: "请求的令牌已过期。"
  },
  kr: {
    signup_email: "이 이메일 주소는 이미 Mandai 계정에서 사용 중입니다.",
    signup_success: "기록을 찾을 수 없습니다.",
    signup_error: "새 사용자 등록 오류입니다.",
    login_success: "로그인 성공.",
    email_no_record: "기록을 찾을 수 없습니다.",
    membership_email_invalid: "요청된 이메일이 유효하지 않거나 비어 있습니다.",
    logout_success: "로그아웃 성공.",
    membership_get_success: "멤버십 획득 성공.",
    email_invalid: "이 이메일 주소는 이미 Mandai 계정에서 사용 중입니다.",
    firstName_invalid: "이름이 유효하지 않습니다.",
    lastName_invalid: "성을 입력한 값이 유효하지 않습니다.",
    dob: "생년월일이 유효하지 않습니다. 만 13세 이상 99세 이하이어야 합니다.",
    group_invalid: "그룹이 유효하지 않습니다.",
    newsletter_invalid: "뉴스레터에 동의하고 구독해야 합니다.",
    country_invalid: "국가가 유효하지 않습니다.",
    phoneNumber_invalid: "전화번호가 유효하지 않습니다.",
    email_not_being_used:
      "이 이메일 주소는 Mandai 계정을 가지고 있지 않습니다.",
    password_invalid: "비밀번호가 일치하지 않습니다.",
    confirmPassword_invalid: "비밀번호가 일치하지 않습니다.",
    update_success: "사용자 정보가 성공적으로 업데이트되었습니다.",
    update_user_error: "사용자 정보 업데이트 오류.",
    old_password_invalid: "기존 비밀번호가 일치하지 않습니다.",
    unauthorized: "권한 없음",
    request_reset_password_success: "비밀번호 재설정 링크가 이메일로 전송되었습니다.",
    confirm_reset_password_success: "비밀번호가 성공적으로 재설정되었습니다.",
    token_reset_password_being_used: "토큰이 이미 사용되었습니다.",
    newPassword_required: "비밀번호가 필요합니다.",
    newPassword_invalid: "비밀번호가 일치하지 않습니다.",
    passwordToken_required: "토큰이 필요합니다.",
    passwordToken_invalid: "요청된 토큰이 유효하지 않거나 비어 있습니다.",
    token_valid: "토큰이 유효합니다.",
    passwordToken_expired: "요청한 토큰이 만료되었습니다."
  },
  ja: {
    signup_email:
      "このメールアドレスはすでにMandaiアカウントで使用されています。",
    signup_success: "記録が見つかりませんでした。",
    signup_error: "新規ユーザー登録エラーです。",
    login_success: "ログイン成功。",
    email_no_record: "記録が見つかりません。",
    membership_email_invalid: "要求されたメールアドレスが無効または空です。",
    logout_success: "ログアウト成功.",
    membership_get_success: "メンバーシップ取得成功.",
    email_invalid:
      "このメールアドレスはすでにMandaiアカウントで使用されています。",
    firstName_invalid: "名前が無効です。",
    lastName_invalid: "苗字が無効です。",
    dob_invalid: "生年月日が無効です。13歳以上99歳以下である必要があります。",
    group_invalid: "グループが無効です。",
    newsletter_invalid: "ニュースレターに同意して購読する必要があります。",
    country_invalid: "国が無効です。",
    phoneNumber_invalid: "電話番号が無効です。",
    email_not_being_used:
      "このメールアドレスはMandaiアカウントを持っていません。",
    password_invalid: "パスワードが複雑性の要件を満たしていません。",
    confirmPassword_invalid: "パスワードが一致しません。",
    update_success: "ユーザー情報が正常に更新されました。",
    update_user_error: "ユーザー情報の更新エラー。",
    old_password_invalid: "古いパスワードが一致しません。",
    unauthorized: "未承認",
    request_reset_password_success: "パスワードリセットリンクをメールに送信しました。",
    confirm_reset_password_success: "パスワードが正常にリセットされました。",
    token_reset_password_being_used: "トークンは既に使用されています。",
    newPassword_required: "パスワードが必要です。",
    newPassword_invalid: "パスワードが複雑性の要件を満たしていません。",
    passwordToken_required: "トークンが必要です。",
    passwordToken_invalid: "要求されたトークンが無効か空です。",
    token_valid: "トークンは有効です。",
    passwordToken_expired: "リクエストされたトークンが期限切れです。"
  },
};
