module.exports = {
  en: {
    signup_email:
      "This email address is already being used for a Mandai Account.",
    signup_firstName: "The first name is invalid.",
    signup_lastName: "The last name is invalid.",
    signup_dob:
      "The date of birth is invalid. Must between 13 and 99 years old.",
    signup_group: "The group is invalid.",
    signup_newsletter: "Must agree and subscribe to the newsletter.",
    signup_country: "Country is invalid.",
    signup_phoneNumber: "Phone number is invalid.",
    signup_password: "Password does not meet complexity requirements.",
    signup_confirmPassword: "Passwords do not match.",
    signup_success: "New user signed up successfully.",
    signup_error: "New user signup error.",
    login_success: "Login success.",
    email_no_record: "No record found.",
    membership_email_invalid: "Requested email is invalid or empty.",
    logout_success: "Logout success.",
    membership_get_success: "Get membership success.",
    email_being_used:
        "This email address is already being used for a Mandai Account.",
    firstName_invalid: "The first name is invalid.",
    lastName_invalid: "The last name is invalid.",
    dob_invalid:
        "The date of birth is invalid. Must between 13 and 99 years old.",
    group_invalid: "The group is invalid.",
    newsletter_invalid: "Must agree and subscribe to the newsletter.",
    country_invalid: "Country is invalid.",
    phoneNumber_invalid: "Phone number is invalid.",
    email_not_being_used: "This email address does not have a Mandai Account."
  },
  zh: {
    signup_email: "此电子邮件地址已被用于 Mandai 帐户。",
    signup_firstName: "名字无效。",
    signup_lastName: "姓氏无效。",
    signup_dob: "出生日期无效。年龄必须在 13 至 99 岁之间。",
    signup_group: "该群组无效。",
    signup_newsletter: "必须同意并订阅新闻通讯。",
    signup_country: "国家无效。",
    signup_phoneNumber: "电话号码无效。",
    signup_password: "密码不符合复杂性要求。",
    signup_confirmPassword: "密码不匹配。",
    signup_success: "新用户注册成功。",
    signup_error: "新用户注册错误。",
    login_success: "登录成功。",
    email_no_record: "未找到记录。",
    membership_email_invalid: "请求的电子邮件无效或为空。",
    logout_success: "注销成功.",
    membership_get_success: "获取会员资格成功.",
    email_being_used: "此电子邮件地址已被用于 Mandai 帐户。",
    firstName_invalid: "名字无效。",
    lastName_invalid: "姓氏无效。",
    dob_invalid: "出生日期无效。年龄必须在 13 至 99 岁之间。",
    group_invalid: "该群组无效。",
    newsletter_invalid: "必须同意并订阅新闻通讯。",
    country_invalid: "国家无效。",
    phoneNumber_invalid: "电话号码无效。",
    email_not_being_used: "此邮箱地址没有 Mandai 账户。"
  },
  kr: {
    signup_email: "이 이메일 주소는 이미 Mandai 계정에서 사용 중입니다.",
    signup_firstName: "이름이 유효하지 않습니다.",
    signup_lastName: "성을 입력한 값이 유효하지 않습니다.",
    signup_dob:
      "생년월일이 유효하지 않습니다. 만 13세 이상 99세 이하이어야 합니다.",
    signup_group: "그룹이 유효하지 않습니다.",
    signup_newsletter: "뉴스레터에 동의하고 구독해야 합니다.",
    signup_country: "국가가 유효하지 않습니다.",
    signup_phoneNumber: "전화번호가 유효하지 않습니다.",
    signup_password: "비밀번호가 일치하지 않습니다.",
    signup_confirmPassword: "비밀번호가 일치하지 않습니다.",
    signup_success: "기록을 찾을 수 없습니다.",
    signup_error: "새 사용자 등록 오류입니다.",
    login_success: "로그인 성공.",
    email_no_record: "기록을 찾을 수 없습니다.",
    membership_email_invalid: "요청된 이메일이 유효하지 않거나 비어 있습니다.",
    logout_success: "로그아웃 성공.",
    membership_get_success: "멤버십 획득 성공.",
    email_invalid: "이 이메일 주소는 이미 Mandai 계정에서 사용 중입니다.",
    firstName_invalid: "이름이 유효하지 않습니다.",
    lastName_invalid: "성을 입력한 값이 유효하지 않습니다.",
    dob:
        "생년월일이 유효하지 않습니다. 만 13세 이상 99세 이하이어야 합니다.",
    group_invalid: "그룹이 유효하지 않습니다.",
    newsletter_invalid: "뉴스레터에 동의하고 구독해야 합니다.",
    country_invalid: "국가가 유효하지 않습니다.",
    phoneNumber_invalid: "전화번호가 유효하지 않습니다.",
    email_not_being_used: "이 이메일 주소는 Mandai 계정을 가지고 있지 않습니다."
  },
  ja: {
    signup_email:
      "このメールアドレスはすでにMandaiアカウントで使用されています。",
    signup_firstName: "名前が無効です。",
    signup_lastName: "苗字が無効です。",
    signup_dob: "生年月日が無効です。13歳以上99歳以下である必要があります。",
    signup_group: "グループが無効です。",
    signup_newsletter: "ニュースレターに同意して購読する必要があります。",
    signup_country: "国が無効です。",
    signup_phoneNumber: "電話番号が無効です。",
    signup_password: "パスワードが複雑性の要件を満たしていません。",
    signup_confirmPassword: "パスワードが一致しません。",
    signup_success: "記録が見つかりませんでした。",
    signup_error: "新規ユーザー登録エラーです。",
    login_success: "ログイン成功。",
    email_no_record: "記録が見つかりません。",
    membership_email_invalid: "要求されたメールアドレスが無効または空です。",
    logout_success: "ログアウト成功.",
    membership_get_success: "メンバーシップ取得成功.",
    email_invalid:
        "このメールアドレスはすでにMandaiアカウントで使用されています。",
    firstName_invalid: "名前が無効です。",
    lastName_invalid: "苗字が無効です。",
    dob_invalid: "生年月日が無効です。13歳以上99歳以下である必要があります。",
    group_invalid: "グループが無効です。",
    newsletter_invalid: "ニュースレターに同意して購読する必要があります。",
    country_invalid: "国が無効です。",
    phoneNumber_invalid: "電話番号が無効です。",
    email_not_being_used: "このメールアドレスはMandaiアカウントを持っていません。"
  },
};
