const resConfig = {
  MEMBERSHIPS_API_RESPONSE_CONFIG_EN:
    '{"MWG_CIAM_USERS_MEMBERSHIPS_SUCCESS":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_SUCCESS","code":200,"message":"Get memberships success.","status":"success"},"MWG_CIAM_USERS_MEMBERSHIPS_NULL":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_NULL","code":200,"message":"No record found.","status":"failed"},"MWG_CIAM_PARAMS_ERR":{"mwgCode":"MWG_CIAM_PARAMS_ERR","code":400,"message":"Wrong parameters.","status":"failed"},"MWG_CIAM_501_ERR":{"mwgCode":"MWG_CIAM_501_ERR","code":501,"message":"Not implemented.","status":"failed"},"MWG_CIAM_USERS_MEMBERSHIPS_EMAIL_ERR":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_EMAIL_ERR","code":200,"message":"Requested email is invalid or empty.","status":"failed"}}',
  MEMBERSHIPS_API_RESPONSE_CONFIG_ZH:
    '{"MWG_CIAM_USERS_MEMBERSHIPS_SUCCESS":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_SUCCESS","code":200,"message":"获得会员资格成功。","status":"success"},"MWG_CIAM_USERS_MEMBERSHIPS_NULL":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_NULL","code":200,"message":"没有找到记录。","status":"failed"},"MWG_CIAM_PARAMS_ERR":{"mwgCode":"MWG_CIAM_PARAMS_ERR","code":400,"message":"Wrong parameters.","status":"failed"},"MWG_CIAM_501_ERR":{"mwgCode":"MWG_CIAM_501_ERR","code":501,"message":"Not implemented.","status":"failed"},"MWG_CIAM_USERS_MEMBERSHIPS_EMAIL_ERR":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_EMAIL_ERR","code":200,"message":"Requested email is invalid or empty.","status":"failed"}}',
  MEMBERSHIPS_API_RESPONSE_CONFIG_KR:
    '{"MWG_CIAM_USERS_MEMBERSHIPS_SUCCESS":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_SUCCESS","code":200,"message":"회원가입에 성공하세요.","status":"success"},"MWG_CIAM_USERS_MEMBERSHIPS_NULL":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_NULL","code":200,"message":"기록을 찾을 수 없습니다.","status":"failed"},"MWG_CIAM_PARAMS_ERR":{"mwgCode":"MWG_CIAM_PARAMS_ERR","code":400,"message":"Wrong parameters.","status":"failed"},"MWG_CIAM_501_ERR":{"mwgCode":"MWG_CIAM_501_ERR","code":501,"message":"Not implemented.","status":"failed"},"MWG_CIAM_USERS_MEMBERSHIPS_EMAIL_ERR":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_EMAIL_ERR","code":200,"message":"Requested email is invalid or empty.","status":"failed"}}',
  MEMBERSHIPS_API_RESPONSE_CONFIG_JP:
    '{"MWG_CIAM_USERS_MEMBERSHIPS_SUCCESS":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_SUCCESS","code":200,"message":"メンバーシップを成功させましょう。","status":"success"},"MWG_CIAM_USERS_MEMBERSHIPS_NULL":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_NULL","code":200,"message":"記録が見つかりませんでした。","status":"failed"},"MWG_CIAM_PARAMS_ERR":{"mwgCode":"MWG_CIAM_PARAMS_ERR","code":400,"message":"Wrong parameters.","status":"failed"},"MWG_CIAM_501_ERR":{"mwgCode":"MWG_CIAM_501_ERR","code":501,"message":"Not implemented.","status":"failed"},"MWG_CIAM_USERS_MEMBERSHIPS_EMAIL_ERR":{"mwgCode":"MWG_CIAM_USERS_MEMBERSHIPS_EMAIL_ERR","code":200,"message":"Requested email is invalid or empty.","status":"failed"}}',
};

module.exports = resConfig;
